.SILENT :
.PHONY : clean
clean : 
	rm -rf __pycache__
	find . -maxdepth 1 -type f ! -name LsbFileSteg.py ! -name test.txt ! -name blah.py ! -name dicom_img_description.csv ! -name dcm2jpg.py ! -name convert.py ! -name Makefile ! -name README -delete
